{{- if .Values.migrate.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  name: {{ .Values.fullnameOverride }}-job
spec:
  template:
    metadata:
      name: {{ .Values.fullnameOverride }}-job
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.fullnameOverride }}-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', '{{ .Values.migrate.command }}']
        imagePullPolicy: Always
        {{- if .Values.migrate.limits }}
        resources:
          limits:
            cpu: {{ .Values.migrate.limits.cpu  |default "500m" }}
            memory: {{ .Values.migrate.limits.memory |default "512Mi" }}
          requests:
            cpu: {{ .limits.cpu  |default "100m" }}
            memory: {{ .Values.migrate.limits.memory  |default "128Mi" }}
        {{- else }}
        resources:
          limits:
            cpu: 500m
            memory: "512Mi" 
          requests:
            cpu: "100m"
            memory: "128Mi"
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ .Values.fullnameOverride }}-cm
          - secretRef:
              name: {{ .Values.fullnameOverride }}-secret
{{ end }}